using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace Bookstore.Api.Contracts;

public sealed class CreateBookRequest : BookWriteRequest, IValidatableObject
{
    // Retain unmapped JSON so validation can detect bookId without making it writable.
    [JsonExtensionData]
    [ValidateNever]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (AdditionalProperties?.Keys.Any(key =>
            string.Equals(key, "bookId", StringComparison.OrdinalIgnoreCase)) == true)
        {
            yield return new ValidationResult(
                "Book ID is generated by the database and must not be supplied when creating a book.",
                ["bookId"]);
        }
    }
}
